### PR TITLE
Fix/image query

### PR DESCRIPTION
**Pull request by touchRED**
Notes:

- Removes references to the inefficient `<Image />` component used before. At the moment, the only remaining places from which to remove this component are the rare instances where it is used to render inline markdown images, like on the individual research topic pages. Not quite sure how we want to do this – it could be best to revert to regular `` tags if necessary. Open to discussion.
- Adjusts image width to 1200 and quality to 80
- Republishes all images on the site to introduce relative paths, allowing graphQL to recognize them as images and run them through the sharp transformer
- Also includes the research topic card hover effect

### CODE REVIEW

**Review by Lane — CHANGES_REQUESTED** [review]
> At the moment, the only remaining places from which to remove this component are the rare instances where it is used to render inline markdown images, like on the individual research topic pages. Not quite sure how we want to do this...

would typicaly handle this with [`gatsby-remark-images`](https://www.gatsbyjs.com/docs/working-with-images-in-markdown/#inline-images-with-gatsby-remark-images) so that images inline with markdown will automatically be transformed.  tried adding this in quick, but doesn't seem to be working.  this site has a bit of a different structure than i'm used to seeing, where everything is in frontmatter in the MDX files, so maybe it's not working because of that?  regardless, it would need some time to troubleshoot and it's not worth the effort at this point so i'm fine leaving it as is with the custom image component.

> Also includes the research topic card hover effect

this looks good, but a couple changes required:

- we want the click area to apply to the entire block.  the [how to build accessible cards](https://www.nomensa.com/blog/how-build-accessible-cards-block-links) article has details on how to achieve this.
- the blocks get a bit thin at some resolutions, can you increase the width from where this goes from 1 column to 2 columns (probably ~960 would be good)

image

**Comment by touchRED** [comment]
@Lane should be good to go, lmk if there's anything I missed

**Comment by Lane** [comment]
@touchRED thanks for the update! the click area of the cards is good and the new breakpoints for cards are also looking good.

i [added a commit](https://github.com/Hyperobjekt/untd-site/pull/122/commits/281015c2e81b533478ae1fedf5aca45923ddf5b0) that changes the structure of the library cards.  the main changes are:

1. remove the link from the "learn more" text, and add it to the heading text.  using "learn more" or "read more" as a link should be avoided because screen readers should be able to determine context from the link text (see [WCAG 2.4.4](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context.html)).  using the heading text as the link gives context about the library section. (see images below)
2. instead of `onClick` on the div, adjust the link style so it covers the entire block (using `:before` with absolute positioning)
3. instead of `onFocus` and `onBlur` handlers, and managing references to DOM elements, use `:focus-within` to handle focus styles.

## Screen reader link navigation (item 1 above)

**before changes**: no context on links

Screen Shot 2021-06-28 at 12 05 45 PM

**after changes**: links with context

Screen Shot 2021-06-28 at 12 04 56 PM

## Required Changes

my changes above address the cards in the research library, but there are also cards in `research-topic.js`.  can you apply these changes there as well?  i think this might conflict with proper heading order in the other ticket, so i didn't want to mess with it.

**Comment by touchRED** [comment]
@Lane ✅

**Review by Lane — APPROVED** [review]

**Pull request merged**
